---
application:
  name: "simpleflashcard"
  project: "SimpleFlashCard"
  organization: "QoveryCommunity"
routers:
- name: "main-simpleflashcard"
  routes:
  - application_name: "simpleflashcard"
    paths:
    - "/BackEnd/*"
