POST http://localhost:3000/pessoa/create HTTP/1.1
content-type: application/json

{
    "txtEmail": "teste1@teste",
    "txtSenha": "123456",
    "nmePessoa":"André"
}

###

POST https://afternoon-garden-95224.herokuapp.com//pessoa/login HTTP/1.1
content-type: application/json

{
    "txtEmail": "teste1@teste",
    "txtSenha": "123456"
}
