name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: Run a BACKEND
      run: |
        cd BackEnd
        npm install
        npm run-script build
        echo "skipping tests"