name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: Run BackEnd - NodeJs
      run: |
        cd BackEnd
        npm install
        npm run-script build
        echo "skipping tests"
    - name: Run FrontEnd - Quasar 
      run:  |
        cd FrontEnd
        npm install -g @quasar/cli
        npm install
        echo "skipping tests"
        quasar build 